### ISSUE TITLE
active_record_bulk_insert

### ISSUE THREAD

**Issue by askinss** [bjhaid/active_record_bulk_insert#4]
I know this question might be off point but I hope I can ask, this is suppose to be active record gem( active_record_bulk_insert) but is there anyway it can be used to bulk insert  data to webservice e.g

contact = Sugarcrm::Contact ({:firstname => "Foo", :lastname => "Bey", :title => 'Mr'})
contact1 = Sugarcrm::Contact ({:firstname => "Foo", :lastname => "Bjhaid", :title => 'Mr'})
bulk_insert([contact, contact1])

**Comment by bjhaid** [comment]
I don't think this is possible.
